import { Scissors, Palette, Dumbbell, Utensils, Camera, Wrench, GraduationCap, Heart, PawPrint, Stethoscope, Scale, Building2, Coffee, Cake, Car, Shirt, Music, Briefcase, LucideIcon } from "lucide-react";
import type { Catalog, CatalogProduct, CatalogPriceItem, CatalogTestimonial } from "@/hooks/useCatalogs";

export interface CatalogTemplate {
  id: string;
  name: string;
  icon: LucideIcon;
  color: string;
  description: string;
  primaryColor: string;
  secondaryColor: string;
  services: { name: string; price: string }[];
  catalog: Partial<Catalog>;
}

export const CATALOG_TEMPLATES: CatalogTemplate[] = [
  {
    id: 'barbearia',
    name: 'Barbearia',
    icon: Scissors,
    color: 'bg-amber-500',
    description: 'Cortes, barbas e tratamentos masculinos',
    primaryColor: '#D97706',
    secondaryColor: '#92400E',
    services: [
      { name: 'Corte Masculino', price: 'R$ 45,00' },
      { name: 'Barba', price: 'R$ 35,00' },
      { name: 'Corte + Barba', price: 'R$ 70,00' },
      { name: 'Degradê', price: 'R$ 50,00' },
    ],
    catalog: {
      title: 'Barbearia Moderna',
      about_title: 'Sobre Nós',
      about_text: 'Somos uma barbearia moderna que une tradição e estilo. Nossos profissionais são especializados em cortes clássicos e tendências atuais, garantindo que você saia com o visual perfeito. Ambiente descontraído, atendimento de qualidade e aquele cafézinho para relaxar enquanto cuida do visual.',
      theme_primary_color: '#D97706',
      theme_secondary_color: '#92400E',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Corte Masculino', description: 'Corte personalizado de acordo com seu estilo e tipo de cabelo. Inclui lavagem e finalização.', price: 'R$ 45,00' },
        { id: crypto.randomUUID(), name: 'Barba Completa', description: 'Aparar, desenhar e hidratar a barba com produtos de alta qualidade para um acabamento impecável.', price: 'R$ 35,00' },
        { id: crypto.randomUUID(), name: 'Combo Completo', description: 'Corte + barba + sobrancelha + hidratação facial. O pacote completo para ficar impecável.', price: 'R$ 85,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Corte Masculino', price: 'R$ 45,00' },
        { id: crypto.randomUUID(), service: 'Barba', price: 'R$ 35,00' },
        { id: crypto.randomUUID(), service: 'Corte + Barba', price: 'R$ 70,00' },
        { id: crypto.randomUUID(), service: 'Degradê', price: 'R$ 50,00' },
        { id: crypto.randomUUID(), service: 'Sobrancelha', price: 'R$ 15,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Carlos Silva', text: 'Melhor barbearia da cidade! Corte sempre perfeito e atendimento nota 10.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Pedro Santos', text: 'Ambiente muito bom, profissionais de primeira. Recomendo demais!', rating: 5 },
        { id: crypto.randomUUID(), name: 'André Costa', text: 'Virei cliente fiel. Qualidade impecável e preço justo.', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'salao',
    name: 'Salão de Beleza',
    icon: Palette,
    color: 'bg-pink-500',
    description: 'Cortes, coloração e tratamentos capilares',
    primaryColor: '#EC4899',
    secondaryColor: '#BE185D',
    services: [
      { name: 'Corte Feminino', price: 'R$ 80,00' },
      { name: 'Escova', price: 'R$ 50,00' },
      { name: 'Coloração', price: 'R$ 150,00' },
      { name: 'Progressiva', price: 'R$ 250,00' },
    ],
    catalog: {
      title: 'Studio de Beleza',
      about_title: 'Sobre Nós',
      about_text: 'Transformamos seu visual com técnicas modernas e produtos de alta qualidade. Nossa equipe é especializada em coloração, cortes e tratamentos capilares, sempre acompanhando as últimas tendências. Venha viver uma experiência única de beleza e bem-estar.',
      theme_primary_color: '#EC4899',
      theme_secondary_color: '#BE185D',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Corte Feminino', description: 'Corte personalizado que valoriza sua beleza natural. Inclui lavagem, corte e finalização.', price: 'R$ 80,00' },
        { id: crypto.randomUUID(), name: 'Coloração Completa', description: 'Coloração profissional com produtos de primeira linha. Cores vibrantes e duradouras.', price: 'R$ 150,00' },
        { id: crypto.randomUUID(), name: 'Hidratação Profunda', description: 'Tratamento intensivo que recupera os fios danificados, devolvendo brilho e maciez.', price: 'R$ 120,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Corte Feminino', price: 'R$ 80,00' },
        { id: crypto.randomUUID(), service: 'Escova', price: 'R$ 50,00' },
        { id: crypto.randomUUID(), service: 'Coloração', price: 'R$ 150,00' },
        { id: crypto.randomUUID(), service: 'Progressiva', price: 'R$ 250,00' },
        { id: crypto.randomUUID(), service: 'Mechas/Luzes', price: 'R$ 200,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Ana Paula', text: 'Adorei! Meu cabelo ficou incrível. Profissionais muito atenciosos.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Juliana Melo', text: 'A coloração ficou exatamente como eu queria. Super recomendo!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Fernanda Lima', text: 'Ambiente aconchegante e equipe maravilhosa. Voltarei sempre!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'restaurante',
    name: 'Restaurante/Delivery',
    icon: Utensils,
    color: 'bg-orange-500',
    description: 'Cardápio e pratos especiais',
    primaryColor: '#F97316',
    secondaryColor: '#C2410C',
    services: [
      { name: 'Prato Executivo', price: 'R$ 25,00' },
      { name: 'Porção', price: 'R$ 35,00' },
      { name: 'Sobremesa', price: 'R$ 15,00' },
      { name: 'Bebidas', price: 'R$ 8,00' },
    ],
    catalog: {
      title: 'Restaurante Sabor & Arte',
      about_title: 'Nossa História',
      about_text: 'Há mais de 10 anos levando sabor e qualidade à sua mesa. Nosso cardápio é preparado diariamente com ingredientes frescos e muito carinho. Seja para um almoço executivo ou um jantar especial, temos o prato perfeito para você. Delivery rápido e eficiente!',
      theme_primary_color: '#F97316',
      theme_secondary_color: '#C2410C',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Prato Executivo', description: 'Arroz, feijão, proteína do dia, salada e guarnição. Porção generosa e sabor caseiro.', price: 'R$ 25,00' },
        { id: crypto.randomUUID(), name: 'Porção de Petiscos', description: 'Seleção de petiscos para compartilhar. Ideal para acompanhar uma boa conversa.', price: 'R$ 35,00' },
        { id: crypto.randomUUID(), name: 'Combo Família', description: 'Porção que serve até 4 pessoas. Inclui proteína, acompanhamentos e bebidas.', price: 'R$ 89,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Prato Executivo', price: 'R$ 25,00' },
        { id: crypto.randomUUID(), service: 'Marmitex P', price: 'R$ 18,00' },
        { id: crypto.randomUUID(), service: 'Marmitex G', price: 'R$ 22,00' },
        { id: crypto.randomUUID(), service: 'Porção', price: 'A partir de R$ 35,00' },
        { id: crypto.randomUUID(), service: 'Sobremesa', price: 'R$ 15,00' },
        { id: crypto.randomUUID(), service: 'Suco Natural', price: 'R$ 8,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Roberto Alves', text: 'Comida caseira de verdade! Sabor inconfundível. Melhor restaurante da região.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Mariana Costa', text: 'Delivery super rápido e comida sempre quentinha. Parabéns!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Lucas Ferreira', text: 'Preço justo e porções generosas. Virei cliente fiel!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'academia',
    name: 'Academia/Personal',
    icon: Dumbbell,
    color: 'bg-green-500',
    description: 'Planos de treino e acompanhamento',
    primaryColor: '#10B981',
    secondaryColor: '#047857',
    services: [
      { name: 'Plano Mensal', price: 'R$ 99,00' },
      { name: 'Plano Trimestral', price: 'R$ 249,00' },
      { name: 'Personal (hora)', price: 'R$ 80,00' },
      { name: 'Avaliação Física', price: 'R$ 50,00' },
    ],
    catalog: {
      title: 'Fitness Center',
      about_title: 'Transforme Seu Corpo',
      about_text: 'Academia completa com equipamentos modernos e profissionais qualificados. Oferecemos acompanhamento personalizado para você alcançar seus objetivos, seja ganho de massa, emagrecimento ou condicionamento físico. Venha fazer parte da nossa família fitness!',
      theme_primary_color: '#10B981',
      theme_secondary_color: '#047857',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Plano Mensal', description: 'Acesso ilimitado a toda a academia, musculação e aulas coletivas.', price: 'R$ 99,00' },
        { id: crypto.randomUUID(), name: 'Personal Trainer', description: 'Treino personalizado com acompanhamento exclusivo de um profissional.', price: 'R$ 80,00/hora' },
        { id: crypto.randomUUID(), name: 'Plano Anual', description: 'Melhor custo-benefício! Acesso completo por 12 meses + avaliação gratuita.', price: 'R$ 799,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Plano Mensal', price: 'R$ 99,00' },
        { id: crypto.randomUUID(), service: 'Plano Trimestral', price: 'R$ 249,00' },
        { id: crypto.randomUUID(), service: 'Plano Semestral', price: 'R$ 449,00' },
        { id: crypto.randomUUID(), service: 'Plano Anual', price: 'R$ 799,00' },
        { id: crypto.randomUUID(), service: 'Personal (hora)', price: 'R$ 80,00' },
        { id: crypto.randomUUID(), service: 'Avaliação Física', price: 'R$ 50,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Thiago Mendes', text: 'Perdi 15kg em 6 meses com o acompanhamento deles. Mudou minha vida!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Camila Rocha', text: 'Ambiente motivador e professores muito atenciosos. Amo treinar aqui!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Bruno Oliveira', text: 'Equipamentos novos e bem cuidados. Melhor academia que já frequentei.', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'estetica',
    name: 'Estética/Spa',
    icon: Heart,
    color: 'bg-rose-500',
    description: 'Tratamentos estéticos e bem-estar',
    primaryColor: '#F43F5E',
    secondaryColor: '#BE123C',
    services: [
      { name: 'Limpeza de Pele', price: 'R$ 120,00' },
      { name: 'Massagem Relaxante', price: 'R$ 100,00' },
      { name: 'Design de Sobrancelhas', price: 'R$ 40,00' },
      { name: 'Depilação', price: 'R$ 60,00' },
    ],
    catalog: {
      title: 'Espaço Bem-Estar',
      about_title: 'Cuide de Você',
      about_text: 'Um refúgio de tranquilidade no coração da cidade. Oferecemos tratamentos estéticos e terapêuticos que renovam corpo e mente. Nossa equipe é especializada em proporcionar momentos de relaxamento e resultados visíveis. Você merece esse cuidado!',
      theme_primary_color: '#F43F5E',
      theme_secondary_color: '#BE123C',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Day Spa', description: 'Pacote completo com limpeza de pele, massagem relaxante e hidratação. 3 horas de puro bem-estar.', price: 'R$ 280,00' },
        { id: crypto.randomUUID(), name: 'Limpeza de Pele', description: 'Tratamento profundo que remove impurezas e renova a pele, deixando-a radiante.', price: 'R$ 120,00' },
        { id: crypto.randomUUID(), name: 'Massagem Relaxante', description: 'Sessão de 60 minutos que alivia tensões e promove relaxamento profundo.', price: 'R$ 100,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Limpeza de Pele', price: 'R$ 120,00' },
        { id: crypto.randomUUID(), service: 'Massagem Relaxante (60min)', price: 'R$ 100,00' },
        { id: crypto.randomUUID(), service: 'Massagem Modeladora', price: 'R$ 120,00' },
        { id: crypto.randomUUID(), service: 'Design de Sobrancelhas', price: 'R$ 40,00' },
        { id: crypto.randomUUID(), service: 'Depilação Completa', price: 'R$ 150,00' },
        { id: crypto.randomUUID(), service: 'Day Spa', price: 'R$ 280,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Patricia Lima', text: 'Saí renovada! O Day Spa é uma experiência incrível. Super recomendo!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Amanda Torres', text: 'Minha pele ficou maravilhosa após o tratamento. Profissionais excelentes!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Renata Souza', text: 'Ambiente acolhedor e atendimento impecável. Meu cantinho de paz!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'fotografia',
    name: 'Fotografia',
    icon: Camera,
    color: 'bg-purple-500',
    description: 'Ensaios, eventos e produtos',
    primaryColor: '#8B5CF6',
    secondaryColor: '#6D28D9',
    services: [
      { name: 'Ensaio Individual', price: 'R$ 350,00' },
      { name: 'Cobertura de Evento', price: 'R$ 800,00' },
      { name: 'Fotos de Produto', price: 'R$ 150,00' },
      { name: 'Edição Avançada', price: 'R$ 50,00' },
    ],
    catalog: {
      title: 'Studio Fotográfico',
      about_title: 'Eternize Seus Momentos',
      about_text: 'Capturamos a essência de cada momento especial. Com equipamentos profissionais e olhar artístico, transformamos suas memórias em imagens inesquecíveis. Seja para um ensaio pessoal, evento corporativo ou fotos de produto, entregamos qualidade e criatividade.',
      theme_primary_color: '#8B5CF6',
      theme_secondary_color: '#6D28D9',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Ensaio Fotográfico', description: 'Sessão de 2 horas com 30 fotos editadas. Inclui consultoria de looks e locação.', price: 'R$ 350,00' },
        { id: crypto.randomUUID(), name: 'Cobertura de Evento', description: 'Cobertura completa do seu evento com entrega de todas as fotos editadas.', price: 'A partir de R$ 800,00' },
        { id: crypto.randomUUID(), name: 'Fotos Still', description: 'Fotografia profissional de produtos para e-commerce e redes sociais.', price: 'R$ 150,00/produto' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Ensaio Individual', price: 'R$ 350,00' },
        { id: crypto.randomUUID(), service: 'Ensaio Casal', price: 'R$ 500,00' },
        { id: crypto.randomUUID(), service: 'Ensaio Família', price: 'R$ 600,00' },
        { id: crypto.randomUUID(), service: 'Cobertura de Evento', price: 'A partir de R$ 800,00' },
        { id: crypto.randomUUID(), service: 'Foto de Produto (unidade)', price: 'R$ 30,00' },
        { id: crypto.randomUUID(), service: 'Edição Avançada', price: 'R$ 50,00/foto' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Carla Mendonça', text: 'As fotos do meu casamento ficaram perfeitas! Captou cada emoção.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Ricardo Gomes', text: 'Profissional incrível! As fotos de produto alavancaram minhas vendas.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Isabela Freitas', text: 'Ensaio maravilhoso! Me senti uma modelo. Super atencioso e criativo.', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'petshop',
    name: 'Pet Shop',
    icon: PawPrint,
    color: 'bg-yellow-500',
    description: 'Banho, tosa e cuidados para pets',
    primaryColor: '#EAB308',
    secondaryColor: '#CA8A04',
    services: [
      { name: 'Banho Pequeno Porte', price: 'R$ 50,00' },
      { name: 'Banho Grande Porte', price: 'R$ 80,00' },
      { name: 'Tosa Higiênica', price: 'R$ 40,00' },
      { name: 'Tosa Completa', price: 'R$ 90,00' },
    ],
    catalog: {
      title: 'Pet Shop Amor Animal',
      about_title: 'Cuidamos do Seu Melhor Amigo',
      about_text: 'Seu pet merece o melhor! Oferecemos serviços de banho, tosa e cuidados especiais com muito carinho e profissionalismo. Nossa equipe ama animais e trata cada peludo como se fosse da família. Venha conhecer nosso espaço aconchegante!',
      theme_primary_color: '#EAB308',
      theme_secondary_color: '#CA8A04',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Banho Completo', description: 'Banho com shampoo especial, secagem, escovação e perfume. Seu pet vai ficar cheiroso!', price: 'A partir de R$ 50,00' },
        { id: crypto.randomUUID(), name: 'Tosa na Tesoura', description: 'Tosa artística feita com carinho e cuidado. Deixamos seu pet ainda mais bonito!', price: 'A partir de R$ 70,00' },
        { id: crypto.randomUUID(), name: 'Spa Pet', description: 'Pacote especial com banho, hidratação, tosa higiênica e corte de unhas.', price: 'R$ 120,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Banho Pequeno Porte', price: 'R$ 50,00' },
        { id: crypto.randomUUID(), service: 'Banho Médio Porte', price: 'R$ 65,00' },
        { id: crypto.randomUUID(), service: 'Banho Grande Porte', price: 'R$ 80,00' },
        { id: crypto.randomUUID(), service: 'Tosa Higiênica', price: 'R$ 40,00' },
        { id: crypto.randomUUID(), service: 'Tosa Completa', price: 'A partir de R$ 90,00' },
        { id: crypto.randomUUID(), service: 'Corte de Unhas', price: 'R$ 20,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Lucia Martins', text: 'Minha cachorrinha adora ir lá! Tratam ela com muito carinho.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Fernando Dias', text: 'Excelente atendimento! Meu gato sempre volta lindo e cheiroso.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Beatriz Ramos', text: 'Profissionais que realmente amam animais. Confiança total!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'confeitaria',
    name: 'Confeitaria/Doces',
    icon: Cake,
    color: 'bg-pink-400',
    description: 'Bolos, doces e sobremesas',
    primaryColor: '#F472B6',
    secondaryColor: '#DB2777',
    services: [
      { name: 'Bolo Decorado', price: 'A partir de R$ 80,00' },
      { name: 'Doces Finos (cento)', price: 'R$ 120,00' },
      { name: 'Cupcakes (dúzia)', price: 'R$ 60,00' },
      { name: 'Torta', price: 'R$ 70,00' },
    ],
    catalog: {
      title: 'Doce Sabor Confeitaria',
      about_title: 'Doçura em Cada Detalhe',
      about_text: 'Criamos doces e bolos com muito amor e dedicação. Cada peça é feita artesanalmente com ingredientes selecionados. Seja para um aniversário especial, casamento ou simplesmente adoçar seu dia, temos a sobremesa perfeita para você!',
      theme_primary_color: '#F472B6',
      theme_secondary_color: '#DB2777',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Bolo Personalizado', description: 'Bolo decorado sob encomenda para festas e eventos. Diversos sabores e tamanhos.', price: 'A partir de R$ 80,00' },
        { id: crypto.randomUUID(), name: 'Kit Festa', description: 'Bolo + 100 docinhos + 12 cupcakes. Tudo o que você precisa para sua festa!', price: 'R$ 350,00' },
        { id: crypto.randomUUID(), name: 'Naked Cake', description: 'O queridinho dos casamentos! Bolo rústico decorado com frutas e flores.', price: 'A partir de R$ 150,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Bolo Simples (1kg)', price: 'R$ 80,00' },
        { id: crypto.randomUUID(), service: 'Bolo Decorado', price: 'A partir de R$ 120,00' },
        { id: crypto.randomUUID(), service: 'Doces Finos (cento)', price: 'R$ 120,00' },
        { id: crypto.randomUUID(), service: 'Brigadeiro Gourmet (cento)', price: 'R$ 150,00' },
        { id: crypto.randomUUID(), service: 'Cupcakes (dúzia)', price: 'R$ 60,00' },
        { id: crypto.randomUUID(), service: 'Torta', price: 'R$ 70,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Sandra Oliveira', text: 'O bolo do meu casamento foi simplesmente perfeito! Lindo e delicioso.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Marcos Paulo', text: 'Os brigadeiros gourmet são viciantes! Não consigo parar de pedir.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Aline Vieira', text: 'Encomendei para o aniversário da minha filha e foi um sucesso!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'cafeteria',
    name: 'Cafeteria',
    icon: Coffee,
    color: 'bg-amber-700',
    description: 'Cafés especiais e lanches',
    primaryColor: '#B45309',
    secondaryColor: '#78350F',
    services: [
      { name: 'Café Espresso', price: 'R$ 6,00' },
      { name: 'Cappuccino', price: 'R$ 10,00' },
      { name: 'Pão de Queijo', price: 'R$ 5,00' },
      { name: 'Fatia de Bolo', price: 'R$ 12,00' },
    ],
    catalog: {
      title: 'Café & Aconchego',
      about_title: 'Seu Cantinho Especial',
      about_text: 'Mais que uma cafeteria, um lugar para relaxar e saborear. Nossos cafés são preparados com grãos selecionados e torrados artesanalmente. Acompanhe com nossos deliciosos quitutes caseiros. WiFi grátis, ambiente acolhedor e aquele cafézinho perfeito!',
      theme_primary_color: '#B45309',
      theme_secondary_color: '#78350F',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Café Coado Especial', description: 'Café de origem única, coado na hora com todo cuidado. Sabor incomparável.', price: 'R$ 8,00' },
        { id: crypto.randomUUID(), name: 'Combo da Manhã', description: 'Café + pão de queijo + suco natural. O combo perfeito para começar o dia!', price: 'R$ 18,00' },
        { id: crypto.randomUUID(), name: 'Frappuccino', description: 'Bebida gelada cremosa com café, leite e calda. Refrescante e deliciosa!', price: 'R$ 15,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Café Espresso', price: 'R$ 6,00' },
        { id: crypto.randomUUID(), service: 'Café Coado', price: 'R$ 5,00' },
        { id: crypto.randomUUID(), service: 'Cappuccino', price: 'R$ 10,00' },
        { id: crypto.randomUUID(), service: 'Latte', price: 'R$ 12,00' },
        { id: crypto.randomUUID(), service: 'Pão de Queijo', price: 'R$ 5,00' },
        { id: crypto.randomUUID(), service: 'Fatia de Bolo', price: 'R$ 12,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Helena Costa', text: 'Melhor café da cidade! Ambiente perfeito para trabalhar ou relaxar.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Gabriel Santos', text: 'O cappuccino é divino! Já virou meu lugar preferido.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Larissa Mendes', text: 'Pão de queijo quentinho e café fresquinho. Não tem erro!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'lavacar',
    name: 'Lava Jato',
    icon: Car,
    color: 'bg-blue-600',
    description: 'Lavagem e estética automotiva',
    primaryColor: '#2563EB',
    secondaryColor: '#1D4ED8',
    services: [
      { name: 'Lavagem Simples', price: 'R$ 40,00' },
      { name: 'Lavagem Completa', price: 'R$ 70,00' },
      { name: 'Polimento', price: 'R$ 150,00' },
      { name: 'Higienização Interna', price: 'R$ 100,00' },
    ],
    catalog: {
      title: 'Auto Brilho Car Wash',
      about_title: 'Seu Carro Merece Brilhar',
      about_text: 'Especialistas em estética automotiva. Utilizamos produtos de alta qualidade e técnicas profissionais para deixar seu veículo impecável. Da lavagem básica ao polimento completo, cuidamos do seu carro com atenção aos detalhes.',
      theme_primary_color: '#2563EB',
      theme_secondary_color: '#1D4ED8',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Lavagem Premium', description: 'Lavagem externa completa + aspiração + silicone nos pneus + perfume.', price: 'R$ 70,00' },
        { id: crypto.randomUUID(), name: 'Polimento Cristalizado', description: 'Tratamento que remove riscos e restaura o brilho original da pintura.', price: 'R$ 250,00' },
        { id: crypto.randomUUID(), name: 'Pacote Completo', description: 'Lavagem + polimento + higienização interna + vitrificação. O carro novo de novo!', price: 'R$ 450,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Lavagem Simples', price: 'R$ 40,00' },
        { id: crypto.randomUUID(), service: 'Lavagem Completa', price: 'R$ 70,00' },
        { id: crypto.randomUUID(), service: 'Polimento', price: 'R$ 150,00' },
        { id: crypto.randomUUID(), service: 'Vitrificação', price: 'R$ 200,00' },
        { id: crypto.randomUUID(), service: 'Higienização Interna', price: 'R$ 100,00' },
        { id: crypto.randomUUID(), service: 'Limpeza de Motor', price: 'R$ 80,00' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Paulo Henrique', text: 'Meu carro ficou parecendo zero km! Serviço impecável.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Daniela Souza', text: 'Atendimento rápido e resultado excelente. Recomendo muito!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Rodrigo Lima', text: 'O polimento ficou incrível. Parece que a pintura foi renovada.', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'moda',
    name: 'Loja de Roupas',
    icon: Shirt,
    color: 'bg-violet-500',
    description: 'Moda feminina, masculina e acessórios',
    primaryColor: '#8B5CF6',
    secondaryColor: '#7C3AED',
    services: [
      { name: 'Camisetas', price: 'A partir de R$ 49,90' },
      { name: 'Calças', price: 'A partir de R$ 99,90' },
      { name: 'Vestidos', price: 'A partir de R$ 89,90' },
      { name: 'Acessórios', price: 'A partir de R$ 29,90' },
    ],
    catalog: {
      title: 'Fashion Store',
      about_title: 'Estilo é Nossa Paixão',
      about_text: 'Trazemos as últimas tendências da moda para você arrasar em qualquer ocasião. Peças exclusivas, qualidade premium e preços justos. Nosso atendimento personalizado ajuda você a encontrar o look perfeito. Vista-se com estilo!',
      theme_primary_color: '#8B5CF6',
      theme_secondary_color: '#7C3AED',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Coleção Verão', description: 'Peças leves e coloridas para os dias quentes. Conforto e estilo em cada detalhe.', price: 'A partir de R$ 49,90' },
        { id: crypto.randomUUID(), name: 'Linha Premium', description: 'Roupas sofisticadas para ocasiões especiais. Tecidos nobres e cortes impecáveis.', price: 'A partir de R$ 149,90' },
        { id: crypto.randomUUID(), name: 'Kit Básico', description: 'Peças essenciais que combinam com tudo. 3 camisetas + 1 calça por um preço especial.', price: 'R$ 199,90' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Camisetas', price: 'A partir de R$ 49,90' },
        { id: crypto.randomUUID(), service: 'Blusas', price: 'A partir de R$ 69,90' },
        { id: crypto.randomUUID(), service: 'Calças', price: 'A partir de R$ 99,90' },
        { id: crypto.randomUUID(), service: 'Vestidos', price: 'A partir de R$ 89,90' },
        { id: crypto.randomUUID(), service: 'Jaquetas', price: 'A partir de R$ 159,90' },
        { id: crypto.randomUUID(), service: 'Acessórios', price: 'A partir de R$ 29,90' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Juliana Farias', text: 'Amo as peças dessa loja! Sempre encontro o que procuro.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Camila Rodrigues', text: 'Atendimento excelente e peças de qualidade. Virei cliente fiel!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Marina Santos', text: 'Preços justos e roupas lindas. Melhor loja da região!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'musica',
    name: 'Aulas de Música',
    icon: Music,
    color: 'bg-indigo-500',
    description: 'Instrumentos e teoria musical',
    primaryColor: '#6366F1',
    secondaryColor: '#4F46E5',
    services: [
      { name: 'Aula Avulsa', price: 'R$ 80,00' },
      { name: 'Pacote Mensal (4 aulas)', price: 'R$ 280,00' },
      { name: 'Aula em Grupo', price: 'R$ 50,00' },
      { name: 'Aula Online', price: 'R$ 60,00' },
    ],
    catalog: {
      title: 'Escola de Música Harmonia',
      about_title: 'Música Para Todos',
      about_text: 'Aprenda música de forma prazerosa e eficiente. Nossa metodologia é adaptada para cada aluno, do iniciante ao avançado. Oferecemos aulas de violão, teclado, bateria, canto e muito mais. Realize seu sonho de tocar seu instrumento favorito!',
      theme_primary_color: '#6366F1',
      theme_secondary_color: '#4F46E5',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Aula Individual', description: 'Aula particular de 1 hora com professor especializado. Aprenda no seu ritmo!', price: 'R$ 80,00' },
        { id: crypto.randomUUID(), name: 'Pacote Trimestral', description: '12 aulas com desconto especial. Evolução garantida com acompanhamento contínuo.', price: 'R$ 750,00' },
        { id: crypto.randomUUID(), name: 'Formação Completa', description: 'Curso completo do básico ao avançado. Inclui material didático e certificado.', price: 'R$ 2.400,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Aula Avulsa (1h)', price: 'R$ 80,00' },
        { id: crypto.randomUUID(), service: 'Pacote Mensal (4 aulas)', price: 'R$ 280,00' },
        { id: crypto.randomUUID(), service: 'Aula em Grupo', price: 'R$ 50,00' },
        { id: crypto.randomUUID(), service: 'Aula Online', price: 'R$ 60,00' },
        { id: crypto.randomUUID(), service: 'Teoria Musical (mensalidade)', price: 'R$ 150,00' },
        { id: crypto.randomUUID(), service: 'Preparatório Conservatório', price: 'R$ 120,00/aula' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Lucas Andrade', text: 'Em 6 meses já estou tocando minhas músicas favoritas! Professor excelente.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Sofia Moreira', text: 'Metodologia incrível! Aprendi mais rápido do que imaginava.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Diego Carvalho', text: 'Ambiente acolhedor e professores apaixonados por música. Recomendo!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
  {
    id: 'consultoria',
    name: 'Consultoria',
    icon: Briefcase,
    color: 'bg-slate-600',
    description: 'Consultoria empresarial e coaching',
    primaryColor: '#475569',
    secondaryColor: '#334155',
    services: [
      { name: 'Consultoria Inicial', price: 'R$ 300,00' },
      { name: 'Mentoria Mensal', price: 'R$ 1.500,00' },
      { name: 'Plano Estratégico', price: 'R$ 2.500,00' },
      { name: 'Workshop', price: 'R$ 500,00/pessoa' },
    ],
    catalog: {
      title: 'Consultoria Estratégica',
      about_title: 'Transforme Seu Negócio',
      about_text: 'Ajudamos empresas a alcançarem seu máximo potencial. Com mais de 15 anos de experiência, oferecemos consultoria especializada em gestão, marketing, finanças e desenvolvimento de equipes. Seu sucesso é nossa missão!',
      theme_primary_color: '#475569',
      theme_secondary_color: '#334155',
      theme_font: 'Inter',
      products: [
        { id: crypto.randomUUID(), name: 'Diagnóstico Empresarial', description: 'Análise completa da sua empresa com relatório detalhado e plano de ação.', price: 'R$ 1.200,00' },
        { id: crypto.randomUUID(), name: 'Mentoria Executiva', description: 'Acompanhamento mensal com reuniões semanais e suporte contínuo.', price: 'R$ 1.500,00/mês' },
        { id: crypto.randomUUID(), name: 'Programa de Transformação', description: 'Consultoria intensiva de 6 meses para reestruturação completa do negócio.', price: 'R$ 12.000,00' },
      ] as CatalogProduct[],
      price_table: [
        { id: crypto.randomUUID(), service: 'Consultoria Inicial (2h)', price: 'R$ 300,00' },
        { id: crypto.randomUUID(), service: 'Diagnóstico Empresarial', price: 'R$ 1.200,00' },
        { id: crypto.randomUUID(), service: 'Mentoria Mensal', price: 'R$ 1.500,00' },
        { id: crypto.randomUUID(), service: 'Plano Estratégico', price: 'R$ 2.500,00' },
        { id: crypto.randomUUID(), service: 'Workshop (por pessoa)', price: 'R$ 500,00' },
        { id: crypto.randomUUID(), service: 'Treinamento In Company', price: 'Sob consulta' },
      ] as CatalogPriceItem[],
      testimonials: [
        { id: crypto.randomUUID(), name: 'Roberto Machado - CEO', text: 'Nossa empresa cresceu 40% após a consultoria. Investimento que valeu cada centavo!', rating: 5 },
        { id: crypto.randomUUID(), name: 'Ana Beatriz - Diretora', text: 'Profissionais extremamente competentes. Mudaram nossa forma de fazer gestão.', rating: 5 },
        { id: crypto.randomUUID(), name: 'Marcelo Lopes - Empresário', text: 'A mentoria me ajudou a sair de uma crise e dobrar o faturamento. Gratidão!', rating: 5 },
      ] as CatalogTestimonial[],
    },
  },
];

export const getTemplateById = (id: string): CatalogTemplate | undefined => {
  return CATALOG_TEMPLATES.find(t => t.id === id);
};
