import { Rect, Circle, IText, FabricObject } from "fabric";

export interface TemplateConfig {
  id: string;
  name: string;
  description: string;
  dimensions: { width: number; height: number };
  bleed: number;
  objects: () => FabricObject[];
}

export const predefinedTemplates: TemplateConfig[] = [
  {
    id: "flyer-modern",
    name: "Flyer Moderno",
    description: "Design minimalista com gradiente",
    dimensions: { width: 1748, height: 2480 },
    bleed: 35,
    objects: () => [
      new Rect({
        left: 0,
        top: 0,
        width: 1748,
        height: 800,
        fill: "#6366f1",
        selectable: true,
      }),
      new IText("SEU TÍTULO AQUI", {
        left: 100,
        top: 200,
        fill: "#ffffff",
        fontSize: 120,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new IText("Subtítulo descritivo do seu evento", {
        left: 100,
        top: 360,
        fill: "#e0e7ff",
        fontSize: 48,
        fontFamily: "Arial",
      }),
      new Rect({
        left: 100,
        top: 900,
        width: 1548,
        height: 400,
        fill: "#ffffff",
        selectable: true,
      }),
      new IText("Descrição do seu produto\nou serviço aqui", {
        left: 150,
        top: 950,
        fill: "#1e293b",
        fontSize: 56,
        fontFamily: "Arial",
      }),
    ],
  },
  {
    id: "business-card-elegant",
    name: "Cartão Elegante",
    description: "Cartão de visita profissional",
    dimensions: { width: 1063, height: 591 },
    bleed: 24,
    objects: () => [
      new Rect({
        left: 0,
        top: 0,
        width: 1063,
        height: 591,
        fill: "#1e293b",
        selectable: false,
      }),
      new Rect({
        left: 50,
        top: 50,
        width: 400,
        height: 8,
        fill: "#f59e0b",
        selectable: true,
      }),
      new IText("SEU NOME", {
        left: 50,
        top: 100,
        fill: "#ffffff",
        fontSize: 48,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new IText("Seu Cargo Profissional", {
        left: 50,
        top: 170,
        fill: "#94a3b8",
        fontSize: 28,
        fontFamily: "Arial",
      }),
      new IText("email@exemplo.com\n(00) 00000-0000", {
        left: 50,
        top: 400,
        fill: "#cbd5e1",
        fontSize: 24,
        fontFamily: "Arial",
      }),
    ],
  },
  {
    id: "pamphlet-promo",
    name: "Panfleto Promocional",
    description: "Design vibrante para promoções",
    dimensions: { width: 2480, height: 3508 },
    bleed: 35,
    objects: () => [
      new Circle({
        left: -200,
        top: -200,
        radius: 600,
        fill: "#ec4899",
        selectable: true,
      }),
      new Circle({
        left: 1800,
        top: 2800,
        radius: 800,
        fill: "#8b5cf6",
        selectable: true,
      }),
      new IText("SUPER\nPROMOÇÃO", {
        left: 200,
        top: 400,
        fill: "#1e293b",
        fontSize: 180,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new Rect({
        left: 200,
        top: 900,
        width: 600,
        height: 200,
        fill: "#fbbf24",
        rx: 20,
        ry: 20,
        selectable: true,
      }),
      new IText("ATÉ 50% OFF", {
        left: 250,
        top: 950,
        fill: "#1e293b",
        fontSize: 72,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new IText("Válido até 31/12/2024\nwww.seusite.com.br", {
        left: 200,
        top: 2800,
        fill: "#475569",
        fontSize: 48,
        fontFamily: "Arial",
      }),
    ],
  },
  {
    id: "flyer-event",
    name: "Flyer Evento",
    description: "Ideal para eventos e festas",
    dimensions: { width: 1748, height: 2480 },
    bleed: 35,
    objects: () => [
      new Rect({
        left: 0,
        top: 0,
        width: 1748,
        height: 2480,
        fill: "#0f172a",
        selectable: false,
      }),
      new Rect({
        left: 874,
        top: 0,
        width: 874,
        height: 2480,
        fill: "#7c3aed",
        selectable: true,
      }),
      new IText("GRANDE\nEVENTO", {
        left: 100,
        top: 400,
        fill: "#ffffff",
        fontSize: 140,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new IText("31 DEZ", {
        left: 950,
        top: 800,
        fill: "#ffffff",
        fontSize: 100,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new IText("Local: Seu Endereço\nHorário: 20h", {
        left: 100,
        top: 1800,
        fill: "#e2e8f0",
        fontSize: 52,
        fontFamily: "Arial",
      }),
    ],
  },
  {
    id: "business-card-minimal",
    name: "Cartão Minimalista",
    description: "Design limpo e moderno",
    dimensions: { width: 1063, height: 591 },
    bleed: 24,
    objects: () => [
      new Rect({
        left: 0,
        top: 0,
        width: 1063,
        height: 591,
        fill: "#ffffff",
        selectable: false,
      }),
      new Rect({
        left: 0,
        top: 0,
        width: 20,
        height: 591,
        fill: "#06b6d4",
        selectable: true,
      }),
      new IText("Nome Completo", {
        left: 80,
        top: 180,
        fill: "#0f172a",
        fontSize: 56,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new IText("Profissão / Cargo", {
        left: 80,
        top: 260,
        fill: "#64748b",
        fontSize: 32,
        fontFamily: "Arial",
      }),
      new IText("+55 (00) 00000-0000", {
        left: 80,
        top: 420,
        fill: "#475569",
        fontSize: 28,
        fontFamily: "Arial",
      }),
      new IText("email@contato.com", {
        left: 80,
        top: 470,
        fill: "#475569",
        fontSize: 28,
        fontFamily: "Arial",
      }),
    ],
  },
  {
    id: "pamphlet-restaurant",
    name: "Panfleto Restaurante",
    description: "Design para cardápio ou promoção",
    dimensions: { width: 2480, height: 3508 },
    bleed: 35,
    objects: () => [
      new Rect({
        left: 0,
        top: 0,
        width: 2480,
        height: 1000,
        fill: "#dc2626",
        selectable: true,
      }),
      new IText("MENU\nESPECIAL", {
        left: 200,
        top: 200,
        fill: "#ffffff",
        fontSize: 200,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new Rect({
        left: 200,
        top: 1200,
        width: 2080,
        height: 300,
        fill: "#fef3c7",
        rx: 10,
        ry: 10,
        selectable: true,
      }),
      new IText("Prato 1 - R$ 29,90", {
        left: 280,
        top: 1280,
        fill: "#78350f",
        fontSize: 64,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new Rect({
        left: 200,
        top: 1600,
        width: 2080,
        height: 300,
        fill: "#fef3c7",
        rx: 10,
        ry: 10,
        selectable: true,
      }),
      new IText("Prato 2 - R$ 34,90", {
        left: 280,
        top: 1680,
        fill: "#78350f",
        fontSize: 64,
        fontWeight: "bold",
        fontFamily: "Arial",
      }),
      new IText("Faça seu pedido:\n(00) 0000-0000", {
        left: 200,
        top: 3000,
        fill: "#1e293b",
        fontSize: 56,
        fontFamily: "Arial",
      }),
    ],
  },
];
