// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Hardcoded values as fallback to ensure connection works
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://ikyrgqxvjvnalnrqibyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlreXJncXh2anZuYWxucnFpYnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NTI4MjMsImV4cCI6MjA3ODUyODgyM30.5ELn_y4HPf7L01sTbq7UAvd23RsmNNgCQju_OkwMuxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type AuthStorage = {
  getItem: (key: string) => string | null;
  setItem: (key: string, value: string) => void;
  removeItem: (key: string) => void;
};

function createMemoryStorage(): AuthStorage {
  const store = new Map<string, string>();
  return {
    getItem: (key) => store.get(key) ?? null,
    setItem: (key, value) => {
      store.set(key, value);
    },
    removeItem: (key) => {
      store.delete(key);
    },
  };
}

// iOS/Safari (principalmente modo privado / in-app browser) pode lançar erro ao usar localStorage.
// Se isso acontecer, caímos para um storage em memória para evitar logout/redirect inesperado.
const memoryStorage = createMemoryStorage();

const safeStorage: AuthStorage = {
  getItem: (key) => {
    try {
      return localStorage.getItem(key);
    } catch {
      return memoryStorage.getItem(key);
    }
  },
  setItem: (key, value) => {
    try {
      localStorage.setItem(key, value);
    } catch {
      memoryStorage.setItem(key, value);
    }
  },
  removeItem: (key) => {
    try {
      localStorage.removeItem(key);
    } catch {
      memoryStorage.removeItem(key);
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
