// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Hardcoded values as fallback to ensure connection works
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://ikyrgqxvjvnalnrqibyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlreXJncXh2anZuYWxucnFpYnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NTI4MjMsImV4cCI6MjA3ODUyODgyM30.5ELn_y4HPf7L01sTbq7UAvd23RsmNNgCQju_OkwMuxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type AuthStorage = {
  getItem: (key: string) => string | null;
  setItem: (key: string, value: string) => void;
  removeItem: (key: string) => void;
};

function createMemoryStorage(): AuthStorage {
  const store = new Map<string, string>();
  return {
    getItem: (key) => store.get(key) ?? null,
    setItem: (key, value) => {
      store.set(key, value);
    },
    removeItem: (key) => {
      store.delete(key);
    },
  };
}

// iOS/Safari (principalmente modo privado / in-app browser) pode falhar no localStorage.
// Caso detectemos qualquer falha, usamos somente memória para evitar sessão “sumir”.
const memoryStorage = createMemoryStorage();

const canUseLocalStorage = (): boolean => {
  try {
    const testKey = "__sb_ls_test__";
    localStorage.setItem(testKey, "1");
    localStorage.removeItem(testKey);
    return true;
  } catch {
    return false;
  }
};

let forceMemoryStorage = !canUseLocalStorage();

const safeStorage: AuthStorage = {
  getItem: (key) => {
    if (forceMemoryStorage) return memoryStorage.getItem(key);

    try {
      const v = localStorage.getItem(key);
      // Em alguns cenários (Safari privado), setItem falha mas getItem não lança erro e retorna null.
      // Se tivermos o valor em memória, preferimos ele para não perder a sessão.
      return v ?? memoryStorage.getItem(key);
    } catch {
      forceMemoryStorage = true;
      return memoryStorage.getItem(key);
    }
  },
  setItem: (key, value) => {
    if (forceMemoryStorage) {
      memoryStorage.setItem(key, value);
      return;
    }

    try {
      localStorage.setItem(key, value);
    } catch {
      forceMemoryStorage = true;
      memoryStorage.setItem(key, value);
    }
  },
  removeItem: (key) => {
    // Sempre limpa a memória também.
    memoryStorage.removeItem(key);

    if (forceMemoryStorage) return;

    try {
      localStorage.removeItem(key);
    } catch {
      forceMemoryStorage = true;
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
