// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded values as fallback to ensure connection works
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ikyrgqxvjvnalnrqibyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlreXJncXh2anZuYWxucnFpYnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NTI4MjMsImV4cCI6MjA3ODUyODgyM30.5ELn_y4HPf7L01sTbq7UAvd23RsmNNgCQju_OkwMuxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});